name = "plumb_rule_prototype"
defaultTargets = ["site"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "cad4b633e75ea769b851f12f9ca3b4f0dfcc625f"

[[lean_lib]]
name = "Docs"

[[lean_exe]]
name = "site"
root = "Main"
